### ISSUE TITLE
ZeroDivisionError

### ISSUE THREAD

**Issue by jinxinsdu** [QuMuLab/PowerfulPuzzling#11]
when trying another picture in the dataset, there will come a ZeroDivisionError.
modify in run.py:
       img, borders = get_image_and_border('dataset\\starry_night\\4_fc.JPG')

run result:
        File "..\PowerfulPuzzling-main\src\border_segmentation\segment_border.py", line 107, in get_ratios
               if ur_i >= ur_len: ur_i = ur_i % ur_len
       ZeroDivisionError: integer division or modulo by zero

**Comment by jyaacoub** [comment]
Hi, sorry for the late response.

It seems to be a problem with the segmentation not being the best. It picks up a lot of noise in this image, would need to tune the `get_image_and_border` function to eliminate that issue.

I have added checks for this in the latest commit so this should not throw errors, but your results will be subpar.
e.g.: (please note that the colors don't mean anything in this instance)
![image](https://user-images.githubusercontent.com/50300488/202969082-01727427-2d40-4a17-9bfa-4ed31d4355e4.png)
